baseurl: "" 
url: "http://jflournoy.gitlab.io" # the base hostname & protocol for your site
title: John C. Flournoy 
subtitle: Estimating uncertainty
author: John C. Flournoy
simple_search: http://google.com/search
description: > # this means to ignore newlines until "baseurl:"
        PhD student at the University of Oregon studying 
        developmental neuroscience and personality. 
name: jcf
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlight: rouge        
permalink: pretty
timezone: America/Los_Angeles
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: [vendor, 'Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
include: [figs]        
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
