baseurl: "" 
url: "http://jflournoy.gitlab.io" # the base hostname & protocol for your site
title: John C. Flournoy 
subtitle: Estimating uncertainty
author: John C. Flournoy
simple_search: http://google.com/search
name: jcf
description: "Academic website for John Flournoy"        
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlight: rouge        
permalink: pretty
timezone: America/Los_Angeles
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: [vendor, 'Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
include: [figs, cv]        
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
